site_name: Ondine
repo_url: https://github.com/jochenalt/Ondine
edit_uri: edit/master/docs
repo_name: Ondine
repo_authorr: 'Jochen Alt'
site_description: Ondine, the beautiful ballet 
pages:
    - 'Home - Ondine?!': 'index.md'
    - 'OmniWheels': 'OmniWheels.md'
    - 'Drive': 'Drive.md'
    - 'Electronics': 'Electronics.md'
    - 'Kinematics': 'Kinematics.md'
    - 'Bill of Material - What is Ondine made of?': 'Bill-of-Material.md'
